#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : amtk
Version  : 5.0.2
Release  : 5
URL      : https://download.gnome.org/sources/amtk/5.0/amtk-5.0.2.tar.xz
Source0  : https://download.gnome.org/sources/amtk/5.0/amtk-5.0.2.tar.xz
Summary  : Actions, Menus and Toolbars Kit
Group    : Development/Tools
License  : LGPL-2.1
Requires: amtk-data = %{version}-%{release}
Requires: amtk-lib = %{version}-%{release}
Requires: amtk-license = %{version}-%{release}
Requires: amtk-locales = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : docbook-xml
BuildRequires : gettext
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : libxslt-bin
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : valgrind

%description
Amtk - Actions, Menus and Toolbars Kit for GTK applications
===========================================================

%package data
Summary: data components for the amtk package.
Group: Data

%description data
data components for the amtk package.


%package dev
Summary: dev components for the amtk package.
Group: Development
Requires: amtk-lib = %{version}-%{release}
Requires: amtk-data = %{version}-%{release}
Provides: amtk-devel = %{version}-%{release}
Requires: amtk = %{version}-%{release}

%description dev
dev components for the amtk package.


%package doc
Summary: doc components for the amtk package.
Group: Documentation

%description doc
doc components for the amtk package.


%package lib
Summary: lib components for the amtk package.
Group: Libraries
Requires: amtk-data = %{version}-%{release}
Requires: amtk-license = %{version}-%{release}

%description lib
lib components for the amtk package.


%package license
Summary: license components for the amtk package.
Group: Default

%description license
license components for the amtk package.


%package locales
Summary: locales components for the amtk package.
Group: Default

%description locales
locales components for the amtk package.


%prep
%setup -q -n amtk-5.0.2
cd %{_builddir}/amtk-5.0.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1585611392
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1585611392
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/amtk
cp %{_builddir}/amtk-5.0.2/COPYING %{buildroot}/usr/share/package-licenses/amtk/01a6b4bf79aca9b556822601186afab86e8c4fbf
%make_install
%find_lang amtk-5

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Amtk-5.typelib
/usr/share/gir-1.0/*.gir

%files dev
%defattr(-,root,root,-)
/usr/include/amtk-5/amtk/amtk-action-info-central-store.h
/usr/include/amtk-5/amtk/amtk-action-info-store.h
/usr/include/amtk-5/amtk/amtk-action-info.h
/usr/include/amtk-5/amtk/amtk-action-map.h
/usr/include/amtk-5/amtk/amtk-application-window.h
/usr/include/amtk-5/amtk/amtk-enum-types.h
/usr/include/amtk-5/amtk/amtk-factory.h
/usr/include/amtk-5/amtk/amtk-gmenu.h
/usr/include/amtk-5/amtk/amtk-init.h
/usr/include/amtk-5/amtk/amtk-menu-item.h
/usr/include/amtk-5/amtk/amtk-menu-shell.h
/usr/include/amtk-5/amtk/amtk-shortcuts.h
/usr/include/amtk-5/amtk/amtk-types.h
/usr/include/amtk-5/amtk/amtk-utils.h
/usr/include/amtk-5/amtk/amtk.h
/usr/lib64/libamtk-5.so
/usr/lib64/pkgconfig/amtk-5.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/gtk-doc/html/amtk-5.0/AmtkActionInfo.html
/usr/share/gtk-doc/html/amtk-5.0/AmtkActionInfoCentralStore.html
/usr/share/gtk-doc/html/amtk-5.0/AmtkActionInfoStore.html
/usr/share/gtk-doc/html/amtk-5.0/AmtkApplicationWindow.html
/usr/share/gtk-doc/html/amtk-5.0/AmtkFactory.html
/usr/share/gtk-doc/html/amtk-5.0/AmtkMenuShell.html
/usr/share/gtk-doc/html/amtk-5.0/amtk-5.0-Amtk-Initialization-and-Finalization.html
/usr/share/gtk-doc/html/amtk-5.0/amtk-5.0-AmtkActionMap.html
/usr/share/gtk-doc/html/amtk-5.0/amtk-5.0-AmtkGmenu.html
/usr/share/gtk-doc/html/amtk-5.0/amtk-5.0-AmtkMenuItem.html
/usr/share/gtk-doc/html/amtk-5.0/amtk-5.0-AmtkShortcuts.html
/usr/share/gtk-doc/html/amtk-5.0/amtk-5.0-AmtkUtils.html
/usr/share/gtk-doc/html/amtk-5.0/amtk-5.0.devhelp2
/usr/share/gtk-doc/html/amtk-5.0/amtk-intro.html
/usr/share/gtk-doc/html/amtk-5.0/annexes.html
/usr/share/gtk-doc/html/amtk-5.0/annotation-glossary.html
/usr/share/gtk-doc/html/amtk-5.0/api-index-2-0.html
/usr/share/gtk-doc/html/amtk-5.0/api-index-3-0.html
/usr/share/gtk-doc/html/amtk-5.0/api-index-4-0.html
/usr/share/gtk-doc/html/amtk-5.0/api-index-5-0.html
/usr/share/gtk-doc/html/amtk-5.0/api-index-full.html
/usr/share/gtk-doc/html/amtk-5.0/api-reference.html
/usr/share/gtk-doc/html/amtk-5.0/home.png
/usr/share/gtk-doc/html/amtk-5.0/index.html
/usr/share/gtk-doc/html/amtk-5.0/left-insensitive.png
/usr/share/gtk-doc/html/amtk-5.0/left.png
/usr/share/gtk-doc/html/amtk-5.0/object-tree.html
/usr/share/gtk-doc/html/amtk-5.0/right-insensitive.png
/usr/share/gtk-doc/html/amtk-5.0/right.png
/usr/share/gtk-doc/html/amtk-5.0/style.css
/usr/share/gtk-doc/html/amtk-5.0/up-insensitive.png
/usr/share/gtk-doc/html/amtk-5.0/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/libamtk-5.so.0
/usr/lib64/libamtk-5.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/amtk/01a6b4bf79aca9b556822601186afab86e8c4fbf

%files locales -f amtk-5.lang
%defattr(-,root,root,-)

